version: '3.9'

services:
  php-apache:
    container_name: php
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - '9000:80'

  mysql:
    container_name: mysql
    image: 'mysql:latest'
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio
